-- Run this once in the Supabase SQL editor (Project -> SQL Editor -> New query -> Run).
-- Sets up the profiles table linked to Supabase Auth users, with Row Level
-- Security so each user can only see and edit their own profile by default.

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  full_name text,
  role text not null default 'worker' check (role in ('worker', 'admin')),
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

drop policy if exists "Users can view their own profile" on public.profiles;
create policy "Users can view their own profile"
  on public.profiles for select
  using (auth.uid() = id);

drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Users can update their own profile"
  on public.profiles for update
  using (auth.uid() = id);

-- Automatically create a profile row whenever a new user signs up.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, new.raw_user_meta_data ->> 'full_name');
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Team chat. Every authenticated employee can read team messages and create
-- messages as themselves. Sender identity is filled by a trusted trigger so it
-- cannot be spoofed by changing the request in the browser.
create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  channel text not null default 'general'
    check (channel in ('general', 'projects', 'workshop')),
  sender_id uuid not null references auth.users (id) on delete cascade,
  sender_name text not null,
  body text not null check (char_length(body) between 1 and 2000),
  created_at timestamptz not null default now()
);

create index if not exists chat_messages_channel_created_at_idx
  on public.chat_messages (channel, created_at desc);

alter table public.chat_messages enable row level security;

drop policy if exists "Team members can read chat messages" on public.chat_messages;
create policy "Team members can read chat messages"
  on public.chat_messages for select
  to authenticated
  using (true);

drop policy if exists "Team members can send chat messages" on public.chat_messages;
create policy "Team members can send chat messages"
  on public.chat_messages for insert
  to authenticated
  with check ((select auth.uid()) = sender_id);

create or replace function public.set_chat_message_sender()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
  resolved_name text;
begin
  new.sender_id := (select auth.uid());

  select coalesce(
    nullif(p.full_name, ''),
    nullif(u.raw_user_meta_data ->> 'full_name', ''),
    nullif(u.raw_user_meta_data ->> 'name', ''),
    nullif(split_part(u.email, '@', 1), ''),
    'Team member'
  )
  into resolved_name
  from auth.users u
  left join public.profiles p on p.id = u.id
  where u.id = (select auth.uid());

  new.sender_name := coalesce(resolved_name, 'Team member');
  return new;
end;
$$;

drop trigger if exists set_chat_message_sender on public.chat_messages;
create trigger set_chat_message_sender
  before insert on public.chat_messages
  for each row execute function public.set_chat_message_sender();

grant select, insert on public.chat_messages to authenticated;
grant usage, select on sequence public.chat_messages_id_seq to authenticated;

-- Postgres Changes is a lightweight fit for this small internal team chat.
-- Add the table once so connected browsers receive new messages immediately.
do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'chat_messages'
  ) then
    alter publication supabase_realtime add table public.chat_messages;
  end if;
end
$$;
